name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Push to master
    runs-on: ubuntu-latest
    env:
        REPO_ORIGIN_VERSION: "0.0.3"
        RELEASE_TAG: "0.0.3.${{ github.run_number }}"
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: make deps
      - name: Build & Test
        run: make build
      - name: Validate release
        uses: goreleaser/goreleaser-action@v1
        with:
          args: release --snapshot --skip-publish --rm-dist

      # official docker actions block

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            dodopizza/sonarcloud-exporter:latest
            dodopizza/sonarcloud-exporter:${{ env.REPO_ORIGIN_VERSION }}
            dodopizza/sonarcloud-exporter:${{ env.RELEASE_TAG }}
          build-args: |
            SHA1=${{ github.sha }}
            TAG=${{ env.RELEASE_TAG }}

      # - official docker actions block

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: dodopizza/sonarcloud-exporter:${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false